project_id = "orrqbsuzxrkoobctkvek"

[functions.generate-world]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.parse-document]
verify_jwt = true

[functions.elevenlabs-scribe-token]
verify_jwt = true

[functions.analyze-content]
verify_jwt = true

[functions.design-world]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.send-contact]
verify_jwt = false

[functions.start-generation]
verify_jwt = true
